# Generated by Django 6.0.1 on 2026-01-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="заголовок")),
                ("content", models.TextField(verbose_name="содержание")),
                ("is_paid", models.BooleanField(default=False, verbose_name="платная")),
                ("youtube_link", models.URLField(blank=True, null=True, verbose_name="ссылка на YouTube")),
                (
                    "images",
                    models.ImageField(blank=True, null=True, upload_to="posts/images/", verbose_name="изображения"),
                ),
                ("views", models.PositiveIntegerField(default=0, verbose_name="просмотры")),
                ("likes", models.PositiveIntegerField(default=0, verbose_name="лайки")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "запись",
                "verbose_name_plural": "записи",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "тег",
                "verbose_name_plural": "теги",
            },
        ),
    ]
