# Generated by Django 6.0.1 on 2026-01-19 21:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "period_months",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1 month"), (3, "3 months"), (6, "6 months"), (9, "9 months"), (12, "12 months")],
                        verbose_name="period in months",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="price",
                    ),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True, verbose_name="start date")),
                ("end_date", models.DateTimeField(verbose_name="end date")),
                ("is_active", models.BooleanField(default=True, verbose_name="is active")),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="Stripe subscription ID"),
                ),
                ("auto_renew", models.BooleanField(default=True, verbose_name="auto renew")),
                (
                    "author",
                    models.ForeignKey(
                        limit_choices_to={"is_author": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscribers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "subscription",
                "verbose_name_plural": "subscriptions",
                "unique_together": {("user", "author")},
            },
        ),
    ]
