# Generated by Django 6.0.1 on 2026-01-20 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "period_months",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 месяц"),
                            (3, "3 месяца"),
                            (6, "6 месяцев"),
                            (9, "9 месяцев"),
                            (12, "12 месяцев"),
                        ],
                        verbose_name="период в месяцах",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="цена",
                    ),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True, verbose_name="дата начала")),
                ("end_date", models.DateTimeField(verbose_name="дата окончания")),
                ("is_active", models.BooleanField(default=True, verbose_name="активна")),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="ID подписки в Stripe"),
                ),
                ("auto_renew", models.BooleanField(default=True, verbose_name="автопродление")),
            ],
            options={
                "verbose_name": "подписка",
                "verbose_name_plural": "подписки",
            },
        ),
    ]
