# Generated by Django 6.0.1 on 2026-01-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Светлая"),
                            ("dark", "Тёмная"),
                            ("neon", "Неон"),
                            ("earth", "Земляные тона"),
                            ("warm", "Тёплый минимализм"),
                            ("high-contrast", "Высокий контраст"),
                            ("sepia", "Сепия / Ретро"),
                        ],
                        default="light",
                        max_length=20,
                        verbose_name="тема",
                    ),
                ),
            ],
            options={
                "verbose_name": "тема",
                "verbose_name_plural": "темы",
            },
        ),
    ]
