# Generated by Django 6.0.1 on 2026-01-20 17:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message", models.TextField(verbose_name="сообщение")),
                ("is_read", models.BooleanField(default=False, verbose_name="прочитано")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="дата создания")),
            ],
            options={
                "verbose_name": "уведомление",
                "verbose_name_plural": "уведомления",
                "ordering": ["-created_at"],
            },
        ),
    ]
