name: Tests

on:
  push:
    branches: [ "develop", "feature/yandex" ]
  pull_request:
    branches: [ "develop", "feature/yandex" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Generate fake SECRET_KEY for tests
      run: |
        echo "SECRET_KEY=$(openssl rand -hex 32)" >> .env
        echo "DEBUG=True" >> .env
        echo "ALLOWED_HOSTS=localhost,127.0.0.1" >> .env
        # Добавь другие обязательные переменные, если нужно
        # echo "DB_NAME=test_db" >> .env
        # etc.

    - name: Erase previous coverage data
      run: coverage erase

    - name: Run tests with coverage
      run: coverage run -m pytest --no-cov-on-fail

    - name: Coverage report
      run: coverage report --fail-under=80

    - name: Coverage HTML
      run: coverage html

    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov/